version: "3.8"

services:
    app-web:
        image: ${PROJECT_NAME}/go-delve:${DOCKER_BUILD_VERSION}
        build: ./docker/delve
        ports: 
            - "8080:80"
            - "2345:2345"
        volumes: 
            - ${APP_API_REL_DIR}:/go/src/${APP_API_DIR}
        working_dir: /go/src/${APP_API_DIR}
        environment:
            - RUN_SAFE=${RUN_SAFE}
        security_opt:
            - apparmor:unconfined
        cap_add:
            - SYS_PTRACE
        restart: always
        container_name: app-web
        command: air -c .air.toml
